# Generated by Django 4.2.10 on 2024-03-27 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sale',
            new_name='bill',
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 3, 27), null=True),
        ),
    ]
