# Generated by Django 4.2.10 on 2024-04-03 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_rename_sale_item_bill_alter_bill_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 4, 3), null=True),
        ),
    ]
