# Generated by Django 4.2.10 on 2024-05-29 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_customer_alter_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 29), null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 29), null=True),
        ),
    ]
