# Generated by Django 4.2.10 on 2024-05-29 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_bill_date_alter_entries_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
