# Generated by Django 4.2.10 on 2024-05-31 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_alter_entries_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 31), null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
