# Generated by Django 4.2.10 on 2024-08-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_alter_bill_date_alter_entries_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
