# Generated by Django 4.2.10 on 2024-08-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_alter_bill_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
